name: POCTyping_File
version: 1.0.0
rundeckPluginVersion: 1.0
author: Leandro Rodrigues
date: 2022-10-18T00:00:00Z
url: http://www.qwsoftware.com.br/
providers:
  - name: ocr_file_typing
    service: WorkflowNodeStep
    title: POC TechMail File Typing
    description: 'Faz o reconhecimento e define o tipo de arquivo.'
    plugin-type: script
    script-interpreter: python3 -u
    script-file: main.py
    script-args: ${config.OCR_SOURCE_DIR} ${config.OCR_DEST_DIR}
    config:
      - type: String
        name: OCR_SOURCE_DIR
        title: Origem
        description: 'Pasta de Origem'
      - type: String
        name: OCR_DEST_DIR
        title: Destino
        description: 'Pasta de Destino'
